#!/usr/bin/env python3
"""Checks tools/i18n-addon/*.json and writes addon/Parley/Locale.lua."""
import json, os, re, subprocess, sys
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
keys = json.loads(subprocess.check_output([sys.executable, os.path.join(ROOT, "tools", "addon_i18n_keys.py")]))
verb = re.compile(r"%[-+# 0]*\d*(?:\.\d+)?[a-zA-Z%]")
def lua(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
ok, out = True, []
out.append("-- Generated by tools/gen_addon_i18n.py from tools/i18n-addon/*.json. Do not edit by hand.")
out.append("-- Parley's in-game text follows the WoW client language (GetLocale).")
out.append("local ADDON, ns = ...")
out.append("")
out.append("local strings = {")
d = os.path.join(ROOT, "tools", "i18n-addon")
for f in sorted(os.listdir(d)):
    code, t = f[:-5], json.load(open(os.path.join(d, f), encoding="utf-8"))
    for k in keys:
        if k not in t:
            print(f"{code}: missing {k!r}"); ok = False
        elif verb.findall(k) != verb.findall(t[k]):
            print(f"{code}: format differs in {k!r}"); ok = False
    for k in t:
        if k not in keys:
            print(f"{code}: unused {k!r}")
    out.append(f"  {code} = {{")
    for k in keys:
        if k in t:
            out.append(f"    [{lua(k)}] = {lua(t[k])},")
    out.append("  },")
out.append("}")
out.append("strings.esMX = strings.esES")
out.append("strings.ptPT = strings.ptBR")
out.append("")
out.append("local loc = GetLocale and GetLocale() or \"enUS\"")
out.append("local active = strings[loc] or {}")
out.append("")
out.append("-- T(\"English text\") returns the text in the client's language.")
out.append("function ns.T(s) return active[s] or s end")
open(os.path.join(ROOT, "addon", "Parley", "Locale.lua"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("addon locales:", ", ".join(x[:-5] for x in sorted(os.listdir(d))), "| keys:", len(keys), "| ok" if ok else "| PROBLEMS")
sys.exit(0 if ok else 1)
