#!/usr/bin/env python3
"""Generate slangdata.go from the MIT-licensed gaming dictionaries of
BabelChat (Andrey Yumashev) and WoW Translator (Pirson).

Input: all.json, a flat dump of their addon/Data/*.lua tables
(one object per term: {"src", "key", "<locale>": "<text>", ...}).
Usage: python3 tools/gen_slang.py all.json > slangdata.go
"""
import json, sys

data = json.load(open(sys.argv[1]))

# Chat shortcuts expanded to plain English before translation (replies, and
# messages translated into a non-English language). Universal gamer terms
# that Parley keeps untranslated (gg, afk, brb, lfg, tank ...) are excluded.
SHORTCUTS = """asap atm bb bk btw cya dw g2g gj gl glhf gn gogo gtg gz hf idc idd idk idm
iamf kk mb ngl np nt nvm nw ofc omg omw pls plz rdy sec smh soz sry thx ttyl ty tyvm
u2 uw w8 wb wp yw dc ez""".split()

# Categories whose terms are worth explaining.
GLOSS_SRC = ("Slang", "Grupos", "Combate", "Estado", "Comercio", "Roles",
             "Hermandad", "Clases", "Classic", "Core", "Social")
# Plain words that need no explanation.
SKIP = set("""sorry guild group party raid need price offer sold dead ghost broken combat
tank tanks heal heals healer healers melee ranged arena mount pet toy trap toxic chill cope
farm grind leader link normal mythic heroic officer recruit hunter warrior paladin druid
frost mount newbie noob gear diff stack spread stun kick burst focus purge dispel enrage
buff debuff honor conquest rated throw cap key skip carry prog glad hero pot vault io bot
copium sweaty clapped pumping bricked go next touch grass sus pog meta lol omg
inc retry sub ac ae pc ffs""".split()) | {"go next", "touch grass"}

LOCALES = ["enUS", "esES", "esMX", "ptBR", "deDE", "frFR", "itIT", "ruRU", "koKR",
           "zhCN", "zhTW", "plPL", "svSE", "noNO", "trTR", "jaJP", "nlNL", "csCZ", "ukUA"]

def src(x):
    return x["src"].split("/")[-1].replace(".lua", "")

# Classic dungeon names first, then BabelChat (bc/), then WoW Translator (wt/).
def prio(x):
    if src(x) == "Classic":
        return 0
    return 1 if x["src"].startswith("bc/") else 2

by_key = {}
for x in sorted(data, key=prio):
    k = x["key"].lower().strip()
    by_key.setdefault(k, x)

def q(s):
    return json.dumps(s, ensure_ascii=False)

out = ["// Code generated by tools/gen_slang.py; DO NOT EDIT.",
       "//",
       "// Gaming terms from BabelChat (c) 2025-2026 Andrey Yumashev and",
       "// WoW Translator (c) 2026 Pirson, both MIT licensed.",
       "// See THIRD_PARTY_NOTICES.md.",
       "",
       "package main",
       "",
       "// shortcuts: chat abbreviations -> plain English.",
       "var shortcuts = map[string]string{"]
for k in sorted(SHORTCUTS):
    x = by_key.get(k)
    if not x or not x.get("enUS"):
        continue
    out.append(f"\t{q(k)}: {q(x['enUS'])},")
out.append("}")
out.append("")
out.append("// glossary: gaming term -> locale -> explanation.")
out.append("var glossary = map[string]map[string]string{")
n = 0
for k, x in sorted(by_key.items()):
    if src(x) not in GLOSS_SRC or k in SKIP or k in SHORTCUTS:
        continue
    en = x.get("enUS", "")
    if not en or en.lower() == k:
        continue
    vals = [f"{q(l)}: {q(x[l])}" for l in LOCALES if x.get(l)]
    out.append(f"\t{q(k)}: {{{', '.join(vals)}}},")
    n += 1
out.append("}")
print("\n".join(out))
print(f"generated {n} glossary terms", file=sys.stderr)
