#!/usr/bin/env python3
"""Checks tools/i18n/*.json against the interface strings and writes i18n_data.go."""
import json, os, re, subprocess, sys
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
keys = json.loads(subprocess.check_output([sys.executable, os.path.join(ROOT, "tools", "i18n_keys.py")]))
verb = re.compile(r"%[-+# 0]*\d*(?:\.\d+)?[a-zA-Z%]")
ok = True
langs = {}
for f in sorted(os.listdir(os.path.join(ROOT, "tools", "i18n"))):
    code = f[:-5]
    d = json.load(open(os.path.join(ROOT, "tools", "i18n", f), encoding="utf-8"))
    for k in keys:
        if k not in d:
            print(f"{code}: missing {k!r}"); ok = False
        elif verb.findall(k) != verb.findall(d[k]) and "%" not in k.replace("%s", "").replace("%d", "").replace("%v", "").replace("%%", "") :
            print(f"{code}: format verbs differ in {k!r}: {d[k]!r}"); ok = False
    for k in d:
        if k not in keys:
            print(f"{code}: unused {k!r}")
    langs[code] = d
out = ["// Code generated by tools/gen_i18n.py from tools/i18n/*.json. DO NOT EDIT.", "", "package main", "",
       "var uiText = map[string]map[string]string{"]
for code, d in langs.items():
    out.append(f"\t{json.dumps(code)}: {{")
    for k in keys:
        if k in d:
            out.append(f"\t\t{json.dumps(k, ensure_ascii=False)}: {json.dumps(d[k], ensure_ascii=False)},")
    out.append("\t},")
out.append("}")
open(os.path.join(ROOT, "i18n_data.go"), "w", encoding="utf-8").write("\n".join(out) + "\n")
subprocess.call(["gofmt", "-w", os.path.join(ROOT, "i18n_data.go")])
print("languages:", ", ".join(langs), "| keys:", len(keys), "| ok" if ok else "| PROBLEMS")
sys.exit(0 if ok else 1)
